services:
    _defaults:
        autowire: true

    Datana\Datapool\Api\DatapoolClient:
        arguments:
            - '%env(DATAPOOL_API_BASE_URI)%'
            - '%env(DATAPOOL_API_USERNAME)%'
            - '%env(DATAPOOL_API_PASSWORD)%'

    Datana\Datapool\Api\AktenApi: ~
    Datana\Datapool\Api\AktenApiInterface: '@Datana\Datapool\Api\AktenApi'

    Datana\Datapool\Api\AktenEventLogApi: ~
    Datana\Datapool\Api\NullAktenEventLogApi: ~

    Datana\Datapool\Api\AktenzeichenApi: ~
    Datana\Datapool\Api\FakeAktenzeichenApi: ~
    
    Datana\Datapool\Api\ChatProtocolApi: ~
    Datana\Datapool\Api\NullChatProtocol: ~    

when@prod:
    services:
        Datana\Datapool\Api\AktenEventLogApiInterface: '@Datana\Datapool\Api\AktenEventLogApi'
        Datana\Datapool\Api\AktenzeichenApiInterface: '@Datana\Datapool\Api\AktenzeichenApi'
        Datana\Datapool\Api\ChatProtocolApiInterface: '@Datana\Datapool\Api\ChatProtocolApi'

when@dev:
    services:
        Datana\Datapool\Api\AktenEventLogApiInterface: '@Datana\Datapool\Api\NullAktenEventLogApi'
        Datana\Datapool\Api\AktenzeichenApiInterface: '@Datana\Datapool\Api\FakeAktenzeichenApi'
        Datana\Datapool\Api\ChatProtocolApiInterface: '@Datana\Datapool\Api\NullChatProtocolApi'

when@test:
    services:
        Datana\Datapool\Api\AktenEventLogApiInterface: '@Datana\Datapool\Api\NullAktenEventLogApi'
        Datana\Datapool\Api\AktenzeichenApiInterface: '@Datana\Datapool\Api\FakeAktenzeichenApi'
        Datana\Datapool\Api\ChatProtocolApiInterface: '@Datana\Datapool\Api\NullChatProtocolApi'
