imports:
<<<<<<< HEAD
    - { resource: "@BitBagSyliusWishlistPlugin/Resources/config/config.yml" }

=======
  - { resource: "@BitBagSyliusWishlistPlugin/Resources/config/config.yml" }
  -
>>>>>>> parent of 3ff4bb1c... Fix recipe for bitbag/wishlist-plugin
